project: null
resume_id: null
name: test_run

val_check_interval: 1.0
metric_reset_interval: 50

# train_dataset: bigbind_act
# val_datasets: [ bigbind_act ]
train_dataset: bigbind_struct
val_datasets: [ bigbind_struct ]

monitor_metric:
  name: val_auroc_all
  mode: max

data:
  
  use_rec: true
  use_lig: true

  sna_frac: 1
  only_ki_kd: false

  num_conformers: 1
  pose_order: shuffle
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

# losses:
#   act_bce:
#     func: bce
#     pred: active_prob_unnorm
#     y: is_active
#     weight: 1.0

losses:
  inv_dist_mse:
    func: inv_dist_mse
    weight: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 500

batch_size: 16

model:

  type: attention_gnn
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 32

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 32

  num_mpnn_layers: 5
  inner_attention: false

  out_size: 16
