resume_id: null
name: test_run
debug_dataset_len: null

val_check_interval: 1.0
metric_reset_interval: 50

train_dataset: bigbind_act
val_datasets: [ bigbind_act ]

monitor_metric:
  name: val/bigbind_act/auroc_all
  mode: max
  # name: val_loss
  # mode: min

data:
  
  use_rec: true
  use_lig: true

  sna_frac: 1
  only_ki_kd: false

  num_conformers: 1
  pose_order: shuffle
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  act_bce:
    func: bce
    pred: active_prob_unnorm
    y: is_active
    weight: 1.0

  diam_mse:
    func: x_mse
    pred: rec_diam
    x: rec_diam
    weight: 0.001

  logp_mse:
    func: x_mse
    pred: lig_clogp
    x: lig_clogp
    weight: 0.01

  logp_x_diam_mse:
    func: x_mse
    pred: clogp_x_diam
    x: clogp_x_diam
    weight: 0.0001

optimizer: adamw
learn_rate: 1e-3
max_epochs: 500

batch_size: 32

model:

  type: attention_gnn_new
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 64

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 64

  num_mpnn_layers: 10
  use_layer_norm: true

  out_sizes: [ 128, 64 ]

