project: null
project_postfix: "pose"
resume_id: null
name: test_run

val_check_interval: null
metric_reset_interval: 500
check_val_every_n_epoch: 10
debug_dataset_len: null

train_dataset: bigbind_struct_v2
val_datasets: [ bigbind_struct ]

monitor_metric:
  name: val/bigbind_struct/acc_2_16
  mode: max

data:

  use_rec: true
  use_lig: true

  pose_sample: best
  num_poses: 1

  sna_frac: 1
  only_ki_kd: false
  
  dock_strategy: "crossdock"

  use_v2_full_rec_data: true

  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type", "atom_residue_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      atom_knn_rad: 5
      residue_knn_rad: 10
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  # pose_mse:
  #   func: diffused_pose_mse
  #   weight: 1.0

  rmsd_mse:
    func: diffused_rmsd_mse
    weight: 1.0

optimizer: adamw
learn_rate: 1e-4
max_epochs: 5000

batch_size: 10

test_inference: true

model:

  type: diffusion_v2

  # rec_encoder:
  #   node_embed_size: 64
  #   edge_embed_size: 64

  # lig_encoder:
  #   node_embed_size: 16
  #   edge_embed_size: 64

  # twist_data:
  #   lig_feat: 64
  #   rec_feat: 32
  #   full_rec_feat: 16

  #   lig_edge_feat: 32
  #   rec_edge_feat: 32

  #   ll_feat: 64
  #   l_ra_feat: 64
  #   l_rf_feat: 16

  # full_atom_embed_size: 16
  # normalization: layer

  # ll_atn_heads: 4
  # ll_atn_feat: 16

  # l_ra_atn_heads: 4
  # l_ra_atn_feat: 16

  # l_rf_atn_heads: 2
  # l_rf_atn_feat: 8

  # rf_ra_hid_size: 8

  # ll_lig_edge_hid_size: 32
  # lig_feat_lig_edge_hid_size: 16

  # rec_feat_rec_edge_hid_size: 16

  # ll_expand_heads: 16
  # ll_expand_feat: 8

  # l_ra_expand_heads: 16
  # l_ra_expand_feat: 8

  # l_rf_expand_heads: 4
  # l_rf_expand_feat: 4
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64

  twist_data:
    lig_feat: 32
    rec_feat: 32
    full_rec_feat: 16

    lig_edge_feat: 32
    rec_edge_feat: 16

    ll_feat: 32
    l_ra_feat: 32
    l_rf_feat: 16

  full_atom_embed_size: 16
  normalization: layer

  mpnn_type: egat  

  lig_mpnn_node_size: 16
  lig_mpnn_edge_size: 16
  lig_mpnn_heads: 4

  rec_mpnn_node_size: 16
  rec_mpnn_edge_size: 16
  rec_mpnn_heads: 4

  ll_atn_heads: 4
  ll_atn_feat: 8

  l_ra_atn_heads: 4
  l_ra_atn_feat: 8

  l_rf_atn_heads: 2
  l_rf_atn_feat: 8

  rf_ra_hid_size: 8

  ll_lig_edge_hid_size: 32
  lig_feat_lig_edge_hid_size: 16

  rec_feat_rec_edge_hid_size: 16

  ll_expand_heads: 4
  ll_expand_feat: 8

  l_ra_expand_heads: 4
  l_ra_expand_feat: 8

  l_rf_expand_heads: 4
  l_rf_expand_feat: 4

  updates_per_block: 2

  num_blocks: 16

  diffusion:
    timesteps: 16
    max_trans_sigma: 4.0
    max_rot_sigma: 1.5
    max_tor_sigma: 1.5
    infer_trans_sigma: 4.0
    use_rot: true
    use_trans: true
    exponent: 2.0
    pred: rmsd
    optim: bfgs

  fix_infer_torsion: false

  rbf_start: 0
  rbf_end: 16
  rbf_steps: 16

  energy_bias: 3.7
