project: null
project_postfix: "pose"
resume_id: null
name: test_run

val_check_interval: 1.0
metric_reset_interval: 50
debug_dataset_len: null

train_dataset: bigbind_struct_v2
val_datasets: [ bigbind_struct_v2 ]

monitor_metric:
  name: val/bigbind_struct_v2/acc_2_16
  mode: max

data:

  use_rec: true
  use_lig: true

  pose_sample: best
  num_poses: 1

  sna_frac: 1
  only_ki_kd: false
  
  dock_strategy: "crossdock"

  # use_embed_crystal_pose: true
  # direct_align_embed_pose: true

  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type", "atom_residue_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      atom_knn_rad: 5
      residue_knn_rad: 10
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  # pose_mse:
  #   func: diffused_pose_mse
  #   weight: 1.0

  rmsd_mse:
    func: diffused_rmsd_mse
    weight: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 5000

batch_size: 16

test_inference: true

model:

  type: diffusion
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 128

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 128

  num_mpnn_layers: 10
  inner_attention: false
  use_layer_norm: true
  multi_pose_attention: true
  intra_lig_energy: true
  asym_lig_energy: true
  energy_bias: 3.7

  project_full_atom: true
  full_atom_embed_size: 32

  out_size: 64

  diffusion:
    timesteps: 16
    max_trans_sigma: 8.0
    max_rot_sigma: 2.0
    max_tor_sigma: 2.0
    infer_trans_sigma: 5.0
    use_rot: true
    use_trans: true
    exponent: 1.5
    energy_rmsd: true
    optim: bfgs

  fix_infer_torsion: true

  rbf_start: 0
  rbf_end: 16
  rbf_steps: 32

  norm_grad: false
  energy_scale: 1.0 #5e-4
