project: null
project_postfix: "pose"
resume_id: null
name: test_run

val_check_interval: 0.1
metric_reset_interval: 50
debug_dataset_len: null

train_dataset: 
  combo:
    - bigbind_struct
    # - bigbind_gnina
    - bigbind_act

val_datasets: [ bigbind_struct ]

monitor_metric:
  name: val/bigbind_struct/acc_2
  mode: max

data:
  
  use_rec: true
  use_lig: true

  pose_sample: best
  num_poses: 1

  sna_frac: 1
  only_ki_kd: false

  max_rec_residues: 40

  remove_feats:
    bigbind_act:
      - rec_graph
      - full_rec_data
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type", "atom_residue_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      atom_knn_rad: 5
      residue_knn_rad: 10
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  # pose_mse:
  #   func: diffused_pose_mse
  #   weight: 1.0

  rmsd_mse:
    func: diffused_rmsd_mse
    weight: 0.5
    task: predict_lig_pose

  uff_rmsd_mse:
    func: diffused_rmsd_mse
    weight: 0.5
    task: null
  

optimizer: adamw
learn_rate: 1e-5
max_epochs: 5000

batch_size: 4

test_inference: true

model:

  type: sym_diffusion
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 128

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 128

  num_mpnn_layers: 10
  inner_attention: false
  normalization: layer
  multi_pose_attention: true
  intra_lig_energy: true
  asym_lig_energy: true
  energy_bias: 2.3

  project_full_atom: true
  full_atom_embed_size: 32

  out_size: 1

  diffusion:
    timesteps: 16
    max_trans_sigma: 4.0
    max_rot_sigma: 1.5
    max_tor_sigma: 1.5
    use_rot: true
    use_trans: true
    exponent: 2.0
    energy_rmsd: true
    optim: bfgs

  rbf_start: 0
  rbf_end: 16
  rbf_steps: 32

  norm_grad: false
  energy_scale: 1.0 #5e-4
