project: null
resume_id: null
name: test_run

val_check_interval: 1.0
metric_reset_interval: 50

train_dataset: bigbind_gnina
val_datasets: [ bigbind_gnina ]

monitor_metric:
  name: val/bigbind_gnina/auroc_all
  mode: max

data:
  
  use_rec: true
  use_lig: true

  sna_frac: 1
  only_ki_kd: false

  pose_sample: best_and_worst
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "atom"
    atom_feats: [ "atom_type", "atom_residue_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "residue_knn"
      atom_knn_rad: 5
      residue_knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  act_bce:
    func: bce
    pred: active_prob_unnorm
    y: is_active
    weight: 0.5
  
  worse_pose_bce:
    func: worse_pose_bce
    weight: 0.5

  # opposite_pose_bce:
  #   func: opposite_pose_bce
  #   weight: 0.5

  # pose_class_bce:
  #   func: pose_class_bce
  #   weight: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 50

batch_size: 4

model:

  type: force_field
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 64

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 64

  num_mpnn_layers: 3
  inner_attention: false
  use_layer_norm: true

  out_size: 16

  rbf_start: 0
  rbf_end: 6
  rbf_steps: 10

  norm_grad: false
  energy_scale: 1e-3
