project: null
resume_id: null
name: test_run

val_check_interval: 0.25
metric_reset_interval: 50
debug_dataset_len: null

train_dataset: 
  combo:
    - bigbind_gnina
    - bigbind_struct_v2

val_datasets: [ bigbind_gnina ]

monitor_metric:
  name: val/bigbind_gnina/auroc_all
  mode: max

data:

  use_rec: true
  use_lig: true

  pose_sample: best_and_worst
  num_poses: 5

  sna_frac: 1
  only_ki_kd: false
  
  dock_strategy: "redock"

  # use_embed_crystal_pose: true
  # direct_align_embed_pose: true

  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type", "atom_residue_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      atom_knn_rad: 5
      residue_knn_rad: 10
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

losses:
  act_bce:
    func: bce
    pred: active_prob_unnorm
    y: is_active
    weight: 1.0
    task: "classify_activity"

  worst_pose_atn_ce:
    func: worse_pose_atn_ce
    weight: 0.1
    task: "classify_activity"

  crystal_pose_ce:
    func: crystal_pose_ce
    weight: 0.1
    task: null

optimizer: adamw
learn_rate: 1e-5
max_epochs: 5000

batch_size: 4

test_inference: true

model:

  type: twister
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    node_out_size: 128

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    node_out_size: 128

  num_mpnn_layers: 8
  normalization: layer
  inner_attention: false

  project_full_atom: true
  full_atom_embed_size: 32

  single_out_size: 32
  interact_hid_size: 128
  interact_dist_in_size: 32
  interact_out_size: 128

  rbf_start: 0
  rbf_end: 8
  rbf_steps: 16
