project: null
resume_id: null
name: test_run

val_check_interval: 1.0

dataset: bigbind_vina
data:
  cache: false
  use_tar: false
  
  use_rec: true
  use_lig: true

  sna_frac: 1
  only_ki_kd: false

  num_conformers: 1
  pose_order: shuffle
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  use_interaction_graph: false
  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

task: ["classification", "pose_rank"]

losses:
  act_ce_lambda: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 50

batch_size: 16
# gpus: [0,1]

sampler:
  max_rec_edges: 10000
  max_lig_edges: 1000

model:

  type: force_field
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    num_mpnn_layers: 2
    edge_hidden_size: 32

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    num_mpnn_layers: 2
    edge_hidden_size: 32

  out_size: 16

  diffusion:
    timesteps: 32
    max_trans_sigma: 0.0
    max_rot_frac: 1.0

  rbf_start: 0
  rbf_end: 16
  rbf_steps: 16

  norm_grad: false
  energy_scale: 1e-3
