project: null
resume_id: null
name: test_run

val_check_interval: 1.0

dataset: bigbind_vina
data:
  cache: false
  use_tar: true
  
  use_rec: true
  use_lig: true

  sna_frac: 1
  only_ki_kd: false

  num_conformers: 1
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 10
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

  interaction_graph:
    dist_cutoff: 10
    max_neighbors: null
    edge_feats: [ "dist"]

task: ["classification", "pose_rank"]

losses:
  act_ce_lambda: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 10

batch_size: 16
# gpus: [0,1]

sampler:
  max_rec_edges: 10000
  max_lig_edges: 1000

model:

  type: interaction_gnn
  
  node_embed_size: 32
  edge_embed_size: 32
  num_mpnn_layers: 2
  edge_hidden_size: 64
  node_hidden_size: 64

  out_size: 512

  out_mlp_sizes: [512, 256, 128, 64]
  dropout_rate: 0.2
